apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
  API_KEY: {{ .Values.secret.apiKey | quote }}
