apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgresql.image }}:{{ .Values.postgresql.tag }}
        ports:
        - containerPort: 5432
          name: postgres
        envFrom:
        - secretRef:
            name: {{ .Values.postgresql.secretName }}
        volumeMounts:
        - name: postgres-data
          mountPath: /bitnami/postgresql
        resources:
          {{- toYaml .Values.postgresql.resources | nindent 10 }}
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.postgresql.storage.storageClass }}
      storageClassName: {{ .Values.postgresql.storage.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.postgresql.storage.size }}
