apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  annotations:
    # ArgoCD Image Updater 설정
    argocd-image-updater.argoproj.io/image-list: backend=ghcr.io/woohyeondev/tube-standard-api
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^[a-f0-9]{40}$
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/backend.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/backend.helm.image-tag: image.tag
spec:
  project: default

  source:
    repoURL: https://github.com/woohyeondev/tube-standard.git  # TODO: Update with your GitOps repo URL
    targetRevision: main  # or master
    path: gitOpsInfra/charts/backend
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default  # TODO: Update with your target namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
