apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
type: Opaque
stringData:
  LMS_ISSUER: {{ .Values.secret.lmsIssuer | quote }}
  LMS_CLIENT_ID: {{ .Values.secret.lmsClientId | quote }}
  TOOL_LAUNCH_URI: {{ .Values.secret.toolLaunchUri | quote }}
  TOOL_LOGIN_ENDPOINT: {{ .Values.secret.toolLoginEndpoint | quote }}
